version: '3.7'

services:
  app:
    build: . 
    working_dir: /bookshelf
    environment:
      HANAMI_ENV: development
      BUNDLE_PATH: /bookshelf/vendor/bundle
    volumes:
      - ./bookshelf:/bookshelf
    ports:
      - 2300
