version: '3.7'

services:
  app:
    build: . 
    working_dir: /bookshelf
    environment:
      HANAMI_ENV: development
      BUNDLE_APP_CONFIG: /bookshelf/.bundle
    volumes:
      - ./bookshelf:/bookshelf
    ports:
      - 2300
    command: 'bundle exec hanami server --host 0.0.0.0'
