version: '3.7'

services:
  app:
    build: . 
    image: hanami
    working_dir: /app
    environment:
      HANAMI_ENV: development
      BUNDLE_APP_CONFIG: /app/.bundle
    volumes:
      - .:/app
    ports:
      - 2300
    command: 'bundle exec hanami server --host 0.0.0.0'
